name: setcover
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.1
  - pip=20.3.3
  - pyspark=3.0.1
  - pytest=6.2.2
  - python=3.8.5
  - setuptools=52.0.0
  - tqdm=4.56.0
  - s3fs
#    get_ipython().system('python -m pip install --upgrade plotly>=4.9 black #kaleido orca')
#    get_ipython().system('python -m pip install tqdm')
#    get_ipython().system('python -m pip install pyspark')
#    get_ipython().system('python -m pip install s3fs')
#    get_ipython().system('python -m pip install pyarrow fastparquet')
#    get_ipython().system('python -m pip install --upgrade --no-deps --force-reinstall git+https://github.com/glennmatlin/pyspark-setcover.git@ec2')