name: setcover
channels:
  - defaults
  - conda-forge
dependencies:
  - pandas=1.2.1
  - pip=20.3.3
  - pyspark=3.0.1
  - pytest=6.2.2
  - python=3.8.5
  - setuptools=52.0.0
  - tqdm=4.56.0
  - s3fs
  - fsspec
  - fastparquet
# pip:
  # --upgrade --no-deps --force-reinstall git+https://github.com/glennmatlin/setcover.git@ec2'
